### ISSUE TITLE
about the temporal module

### ISSUE THREAD

**Issue by yuzhongruicn** [G-U-N/Be-Your-Outpainter#10]
Hi! Thanks for sharing such great work!

I have a question about the temporal module you are using. According to your paper, your temporal module is initialized with AnimateDiff's. Did you fine-tune it, or just directly integrate in your model? 

Thanks!

**Comment by G-U-N** [comment]
Thanks for the interest. Direct integration. But I think fine-tuning can make it better.

**Comment by yuzhongruicn** [comment]
Thanks!
