### ISSUE TITLE
Will the code become available and questions on pipeline.

### ISSUE THREAD

**Issue by stanathong** [G-U-N/Be-Your-Outpainter#3]
Hello, your work on video outpainting is very impressive!

I have a couple of questions and look forward to your answers :)

1. Will the code become available at any point and if so, when?
2. How did you outpaint a video using AnimateDiff? Can you explain how you manage to do that please?

Thank you very much!

**Comment by G-U-N** [comment]
The basic code is released. Thanks for the interest!

**Comment by stanathong** [comment]
Appreciate it! Thank you so much!
