### ISSUE TITLE
K value

### ISSUE THREAD

**Issue by Levishery** [G-U-N/Be-Your-Outpainter#5]
Excellent work. In the output dir there are results with different K values(1/2, 1, 2). Which value are used in the paper?

**Comment by greasebig** [comment]
what k mean and what it used for? why set k=1 1.5 2?

**Comment by greasebig** [comment]
do you have ablation experiment table of k? why choose 1 1.5 2?

**Comment by G-U-N** [comment]
K is set to 1/2 by default.

**Comment by G-U-N** [comment]
Setting K small will reduce the copying phenomena in the outpainting results, especially for the challenging setting with ratio 0.66.
