### ISSUE TITLE
What configuration to tune to avoid out of memory error?

### ISSUE THREAD

**Issue by stanathong** [G-U-N/Be-Your-Outpainter#6]
Hi again, 

I tried to execute run.sh in which I kept only one task (SB_dog1) in config/exp.yaml. However, I faced with out of memory issue. 

I understand that it requires a lot of memory but wondering if there are any parameters in config/exp.yaml or elsewhere I could adjust to reduce the amount of memory usage. 

Thank you very much for your help.

**Comment by G-U-N** [comment]
I tested on my device, and it reported 17 GB memory peak.

Set [this line](https://github.com/G-U-N/Be-Your-Outpainter/blob/master/configs/base-lora.yaml#L32)  as True should help reduce the memory. 

After this being enabled, it reported 10 GB memory peak.

LMK if you have any questions.

**Comment by stanathong** [comment]
That actually solved my memory issue. Thank you for your help.
