### ISSUE TITLE
Long video outpainting

### ISSUE THREAD

**Issue by Levishery** [G-U-N/Be-Your-Outpainter#7]
Hi,
    I noticed that currently, the inference does not support long video outpainting. The window size and stride parameters are not used in the inference pipeline. 
    When will the code be updated?

**Comment by greasebig** [comment]
really? how long it support now? 5s 10s?

**Comment by G-U-N** [comment]
Thanks for the attention. I am cleaning it.

**Comment by Levishery** [comment]
> really? how long it support now? 5s 10s?

32 frames, 4s (fps=8).

**Comment by G-U-N** [comment]
The basic long outpainting pipeline is uploaded. Please refer to [run_long.sh](https://github.com/G-U-N/Be-Your-Outpainter/blob/master/run_long.sh).
